// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyOe1WCTcJ_PiHSS6QSm-_J3Tkwt_rmM',
    appId: '1:299843107216:web:fb1ebd7ee83131ad91db15',
    messagingSenderId: '299843107216',
    projectId: 'shineportal-ktt',
    authDomain: 'shineportal-ktt.firebaseapp.com',
    storageBucket: 'shineportal-ktt.appspot.com',
    measurementId: 'G-1YVYJFQ0H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCelXTlpJfr353id-iCrxkLIAUd8svUiaQ',
    appId: '1:299843107216:android:1ae423bc678f219a91db15',
    messagingSenderId: '299843107216',
    projectId: 'shineportal-ktt',
    storageBucket: 'shineportal-ktt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqKF76VXxta31PfrwBv8SWL5upE24aVV8',
    appId: '1:299843107216:ios:0f47f88ad0f6045791db15',
    messagingSenderId: '299843107216',
    projectId: 'shineportal-ktt',
    storageBucket: 'shineportal-ktt.appspot.com',
    iosBundleId: 'com.kttprojects.shinePortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqKF76VXxta31PfrwBv8SWL5upE24aVV8',
    appId: '1:299843107216:ios:1af5502e064310ea91db15',
    messagingSenderId: '299843107216',
    projectId: 'shineportal-ktt',
    storageBucket: 'shineportal-ktt.appspot.com',
    iosBundleId: 'com.kttprojects.shinePortal.RunnerTests',
  );
}
